/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', 'node_modules/flowbite-react/lib/esm/**/*.js'],
  theme: {
    extend: {
      fontFamily: {
        roboto: ['Roboto', 'sans-serif'],
      },
      fontSize: {
        'heading-1': '3.375rem',
        'heading-2': '2.625rem',
        'heading-3': '2rem',
        'heading-4': '1.5rem',
        'heading-5': '1.25rem',
        'heading-6': '1.125rem',
        'body-L': '1.125rem',
        'body-M': '1rem',
        'body-S': '0.875rem',
        'body-XS': '0.75rem',
        'body-XXS': '0.625rem',
        'subtitle-M': '1rem',
        'subtitle-S': '0.875rem',
        caption: '1.125rem',
        menu: '1rem',
        'button-L': '1.125rem',
        'button-M': '1rem',
        'button-S': '0.875rem',
      },
      fontWeight: {
        heading: '700',
        body: '400',
        subtitle: '500',
        caption: '700',
        menu: '500',
        button: '500',
      },
      colors: {
        background: 'hsl(var(--background))',
        primary: 'hsl(var(--primary))',
        secondary: 'hsl(var(--secondary))',
        'base-color': 'hsl(var(--base-color))',
        'base-outline': 'hsl(var(--base-outline))',
        default: {
          white: '#FFFFFF',
          alert: '#DA1E28',
          warning: '#F1C21B',
          success: '#25A249',
          overlay: '#121619',
        },
        gray: {
          50: 'hsl(var(--gray-50))',
          100: 'hsl(var(--gray-100))',
          200: 'hsl(var(--gray-200))',
          300: 'hsl(var(--gray-300))',
          400: 'hsl(var(--gray-400))',
          500: 'hsl(var(--gray-500))',
          600: 'hsl(var(--gray-600))',
          700: 'hsl(var(--gray-700))',
          800: 'hsl(var(--gray-800))',
          900: 'hsl(var(--gray-900))',
          950: 'hsl(var(--gray-950))',
        },
        neutral: {
          50: 'hsl(var(--neutral-50))',
          100: 'hsl(var(--neutral-100))',
          200: 'hsl(var(--neutral-200))',
          300: 'hsl(var(--neutral-300))',
          400: 'hsl(var(--neutral-400))',
          500: 'hsl(var(--neutral-500))',
          600: 'hsl(var(--neutral-600))',
          700: 'hsl(var(--neutral-700))',
          800: 'hsl(var(--neutral-800))',
          900: 'hsl(var(--neutral-900))',
          950: 'hsl(var(--neutral-950))',
        },
      },
      borderRadius: {
        '0xl': '0.625rem',
      },
      width: {
        20: '5rem',
        25: '6.25rem',
        150: '37.5rem',
        160: '40rem',
        170: '42.5rem',
        180: '45rem',
      },
      backgroundImage: {
        building: "url('../assets/Building.svg')",
      },
    },
  },
  plugins: [require('flowbite/plugin')],
};
